config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   # Commented to prevent defaulting to sign in view to check if signed in or not
    devise_scope :user do
      root 'devise/sessions#new'
    end

  resources :recipes
  
  resources :recipe_foods

  resources :public_recipes

  resources :foods, except: [:update]

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
  end

  resources :users, only: [:index, :show]

  get '/shopping_list', to: 'shopping_list#index', as: 'shopping_list'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :recipes
    
      resources :recipe_foods
  
      resources :public_recipes
  
      resources :foods, except: [:update]
  
      resources :recipes, only: [:index, :show, :new, :create, :destroy] do
        resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
      end
  
      resources :users, only: [:index, :show]

      get '/shopping_list', to: 'shopping_list#index', as: 'shopping_list'
    end
  end
  
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  has_many :recipe_foods, foreign_key: :recipe_id, dependent: :delete_all

  validates :name, presence: true, length: { maximum: 250 }

  validates :description, presence: true

  validates :preparation_time, presence: true

  validates :cooking_time, presence: true
end

app/controllers/api/v1/recipes_controller.rb
class Api::V1::RecipesController < ApplicationController
  load_and_authorize_resource

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all.includes(:user).filter { |recip| recip.user_id == current_user.id }
    respond_to do |format|
      format.json { render json: @recipes, status: 200 }
    end
  end

  def show
    @recipe = Recipe.find_by(id: params[:id])
    respond_to do |format|
      format.json { render json: @recipe, status: 200 }
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.json { render json: @recipe, status: :ok }
      else
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
    # redirect_to recipes_url
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end

  private :recipe_params
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all.includes(:user).filter { |recip| recip.user_id == current_user.id }
    respond_to do |format|
      format.html
      format.json { render json: @recipes, status: 200 }
    end
  end

  def show
    @recipe = Recipe.find_by(id: params[:id])
    respond_to do |format|
      format.html { redirect_to recipes_path, notice: 'Recipe found' unless @recipe }
      format.json { render json: @recipe, status: 200 }
    end
    # end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end

  private :recipe_params
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>

  <p>
    <strong>Preparation time:</strong>
    <%= recipe.preparation_time %>
  </p>

  <p>
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= recipe.public %>
  </p>

  <p>
    <strong>User:</strong>
    <%= recipe.user_id %>
  </p>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<main>

        <section class="recipe_section1">
            <% @recipes.each do |recipe| %>
            <article class="recipe_section1_article">
                <header class="recipe_section1_article_header">
                    <h2><%= link_to recipe.name, recipe_path(recipe), class: "td_none" %></h2>
                    <button class="custom_btn1">
                     <%= link_to "Remove", recipe_path(recipe), class: "td_none custom_color1", data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete Recipe?" } %> 
                     </button>
                </header>

                <div class="recipe_section1_article_div">
                    <h3>Description of the recipe</h3>
                    <p><%= recipe.description %></p>  
                </div>
            </article>
            <% end %>

        </section>

        <section class="custom_text_align1 custom_margin1">
        <button class="custom_btn1"><%= link_to "Add New Recipe", new_recipe_path, class: "custom_font2 td_none custom_color1" %> </button>
        </section>
        
    </main>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<main>

    <section class="recipe_detail_section1">

            <header>
                <h2><%= @recipe.name%></h2>
            </header>

            <article class="recipe_detail_section1_article">

                <div class="recipe_detail_section1_article_div1">
                    <p>Preparation time: <%= @recipe.preparation_time %></p>
                    <p>Cooking time: <%= @recipe.cooking_time %></p>
                    <p>Steps: <%= @recipe.description %></p> 
                </div>

                <div class="recipe_detail_section1_article_div2">
                    <p>Public</p>
                    <div>
                    <% if @recipe.public %>
                    <label class="switch">
                        <input type="checkbox" checked>
                        <span class="slider round"></span>
                    </label>
                    <% end %>

                    <% if !@recipe.public %>
                    <label class="switch">
                        <input type="checkbox">
                        <span class="slider round"></span>
                    </label>
                    <% end %>
                    </div>
                    
                </div>

            </article>

    </section>

    <section class="recipe_detail_section2">
            <button class="custom_btn1"><%= link_to 'Generate Shopping List', shopping_list_path, class:"td_none custom_color1" %></button>
            <button class="custom_btn1">
            <%=link_to "Add ingredient", new_recipe_recipe_food_path(@recipe), class:"td_none custom_color1"%>
            </button>
        </section>

        <section class="recipe_detail_section3">

            <table class="styled_table">

                <thead>
                    <tr>
                        <th>Food</th>
                        <th>Quantity</th>
                        <th>Value</th>
                        <th>Actions</th>
                    </tr>
                </thead>

                <tbody> 

                <% @recipe.recipe_foods.each do |recipeFood|%> 
                    <tr class="active_row custom_row1"> 
                        <th class="custom_font1"><%= recipeFood.food.name%></th>
                        <th class="custom_font1"><%= recipeFood.quantity %><%= recipeFood.food.measurement_unit  %></th>
                        <th class="custom_font1">$<%= recipeFood.quantity.to_i * recipeFood.food.price %></th>
                        <th class="custom_font1 table_flex1">
                        <button class="custom_btn1"><%=link_to "Modify", edit_recipe_recipe_food_path(recipe_id: @recipe.id, id:recipeFood.id), class:"td_none custom_color1"%></button>
                        <%=button_to "Delete", recipe_recipe_food_path(recipe_id: @recipe.id, id: recipeFood.id), method: :delete, class:"custom_btn1 custom_color1"%>
                        </th>
                    </tr>
                <% end %> 

                </tbody>

            </table>

    </section>

</main>