config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   # Commented to prevent defaulting to sign in view to check if signed in or not
    devise_scope :user do
      root 'devise/sessions#new'
    end

  resources :recipes
  
  resources :recipe_foods

  resources :public_recipes

  resources :foods, except: [:update]

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
  end

  resources :users, only: [:index, :show]

  get '/shopping_list', to: 'shopping_list#index', as: 'shopping_list'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :recipes
    
      resources :recipe_foods
  
      resources :public_recipes
  
      resources :foods, except: [:update]
  
      resources :recipes, only: [:index, :show, :new, :create, :destroy] do
        resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
      end
  
      resources :users, only: [:index, :show]

      get '/shopping_list', to: 'shopping_list#index', as: 'shopping_list'
    end
  end
  
  
end

app/views/shared_features/_footer.html.erb
<footer class="footer_box">
    <div>
        <p>Copyright &#169; Wetty 2023</p>
    </div>
</footer>

app/views/shared_features/_header.html.erb
<header class="nav_header">
    <div class="logo_box list_style_none">
        <li><%= link_to "Wetty", foods_path, class:"td_none" %></li>
        
    </div>

    <nav class="nav_box">
        <ul class="list_style_none">
            <li><%= link_to "Users", users_path, class:"td_none" %></li>
            <li><%= link_to "Recipes", recipes_path, class:"td_none" %></li>
            <li><%= link_to "Foods", foods_path, class:"td_none" %></li>
            <li><%= link_to "Public Recipes", public_recipes_path, class:"td_none" %></li>
            <li><% if user_signed_in? %>
             <%= button_to ('Sign Out'), destroy_user_session_path, method: :delete, form: {  data: { turbo: :false } }, class:"custom_btn2 td_none" %>
            <% end %></li>
            
        </ul>
    </nav>
</header>