config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   # Commented to prevent defaulting to sign in view to check if signed in or not
    devise_scope :user do
      root 'devise/sessions#new'
    end

  resources :recipes
  
  resources :recipe_foods

  resources :public_recipes

  resources :foods, except: [:update]

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
  end

  resources :users, only: [:index, :show]

  get '/shopping_list', to: 'shopping_list#index', as: 'shopping_list'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :recipes
    
      resources :recipe_foods
  
      resources :public_recipes
  
      resources :foods, except: [:update]
  
      resources :recipes, only: [:index, :show, :new, :create, :destroy] do
        resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
      end
  
      resources :users, only: [:index, :show]

      get '/shopping_list', to: 'shopping_list#index', as: 'shopping_list'
    end
  end
  
  
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user

  has_many :recipe_foods, foreign_key: :recipe_id, dependent: :delete_all

  validates :name, presence: true, length: { maximum: 250 }

  validates :measurement_unit, presence: true

  validates :price, presence: true

  validates :quantity, presence: true
end

app/controllers/api/v1/foods_controller.rb
class Api::V1::FoodsController < ApplicationController
  load_and_authorize_resource

  # GET /foods or /foods.json
  def index
    @foods = Food.all.includes(:user).filter { |foo| foo.user_id == current_user.id }
    respond_to do |format|
      format.json { render json: @foods, status: 200 }
    end
  end

  #  GET /foods/1 or /foods/1.json
  def show
    @food = Food.find_by(id: params[:id])
    respond_to do |format|
      format.json { render json: @food, status: 200 }
    end
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id
    respond_to do |format|
      if @food.save
        format.json { render json: @food, status: :created }
      else
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @food.update(food_params)
        format.json { render json: @food, status: 200 }
      else
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @food.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end

  private :food_params
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource

  # before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.all.includes(:user).filter { |foo| foo.user_id == current_user.id }
    respond_to do |format|
      format.html
      format.json { render json: @foods, status: 200 }
    end
  end

  #  GET /foods/1 or /foods/1.json
  def show
    @food = Food.find_by(id: params[:id])
    respond_to do |format|
      format.html { redirect_to foods_path, notice: 'Food found' unless @user }
      format.json { render json: @user, status: 200 }
    end
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id

    respond_to do |format|
      if @food.save
        format.html { redirect_to root_path, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully deled.' }
      format.json { head :no_content }
    end
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end

  private :food_params
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Measurement unit:</strong>
    <%= food.measurement_unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= food.quantity %>
  </p>

  <p>
    <strong>User:</strong>
    <%= food.user_id %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<main>

        <section class="food_section1">
            <button class="custom_btn1"><%= link_to "Add Food", new_food_path, class: "td_none custom_color1" %></button>
        </section>

        <section class="food_section2">
            <table class="styled_table">

                <thead>
                    <tr>
                        <th>Food</th>
                        <th>Measurement unit</th>
                        <th>Unit Price</th>
                        <th>Actions</th>
                    </tr>
                </thead>

                <tbody> 
                <% @foods.each do |food| %>
                    <tr class="active_row custom_row1">
                        <th class="custom_font1"><%= food.name %></th>
                        <th class="custom_font1"><%= food.measurement_unit %></th>
                        <th class="custom_font1">$<%= food.price %></th>
                        <th class="custom_font1 table_flex1">
                            <button class="custom_btn1"><%= link_to "Delete", food_path(food), class:"td_none custom_color1", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></button> 
                        </th>
                    </tr>
                <% end %>
                </tbody>

            </table>
        </section>
    </main>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>


<main>
        <section class="shopping_list1">
            <header>
                <h2>Shopping List</h2>
            </header>
        </section>

        <section class="shopping_list2">

            <article>
                <div>
                    <p>Amount of food items to buy: 3</p>
                </div>
                <div>
                    <p>Total value of food needed: $894</p>
                </div>
            </article>

            <table class="styled_table">

                <thead>
                    <tr>
                        <th>Food</th>
                        <th>Quantity</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody> 
                    <tr class="active_row custom_row1">
                        <th class="custom_font1">Apple</th>
                        <th class="custom_font1">20g</th>
                        <th class="custom_font1">$100</th>
                    </tr>

                </tbody>

            </table>


        </section>
    </main>