config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   # Commented to prevent defaulting to sign in view to check if signed in or not
    devise_scope :user do
      root 'devise/sessions#new'
    end

  resources :recipes
  
  resources :recipe_foods

  resources :public_recipes

  resources :foods, except: [:update]

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
  end

  resources :users, only: [:index, :show]

  get '/shopping_list', to: 'shopping_list#index', as: 'shopping_list'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :recipes
    
      resources :recipe_foods
  
      resources :public_recipes
  
      resources :foods, except: [:update]
  
      resources :recipes, only: [:index, :show, :new, :create, :destroy] do
        resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
      end
  
      resources :users, only: [:index, :show]

      get '/shopping_list', to: 'shopping_list#index', as: 'shopping_list'
    end
  end
  
  
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true
end

app/controllers/api/v1/recipe_foods_controller.rb
class Api::V1::RecipeFoodsController < ApplicationController
  load_and_authorize_resource

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new(recipe_food_params.merge(recipe_id: @recipe.id))
    if @recipe_food.save
      respond_to do |format|
        format.json { render json: @recipe_food, status: :created }
      end
    else
      respond_to do |format|
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @recipe.user_id = current_user.id
    @recipe_food = RecipeFood.find(params[:id])
    respond_to do |format|
      format.json { render json: [@recipe, @recipe_food], status: 200 }
    end
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(recipe_food_params)
      respond_to do |format|
        format.json { render json: @recipe_food, status: 200 }
      end
    else
      respond_to do |format|
        format.json { render json: @recipe_food, status: :unprocessable_entity }
      end
    end
    # redirect_to recipe_path(@recipe_food.recipe_id)
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end

  private :recipe_food_params
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new(recipe_food_params.merge(recipe_id: @recipe.id))
    if @recipe_food.save
      flash[:notice] = 'Food created sucessfully.'
      redirect_to @recipe
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @recipe.user_id = current_user.id
    @recipe_food = RecipeFood.find(params[:id])
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(recipe_food_params)
      flash[:success] = 'Recipe Food updated successfully.'
    else
      flash[:error] = 'Could not add'
    end
    redirect_to recipe_path(@recipe_food.recipe_id)
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    flash[:success] = 'Recipe Food deleted successfully.'
    redirect_to recipe_path(@recipe_food.recipe_id)
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end

  private :recipe_food_params
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_form.html.erb
<h4>Add Recipe Food</h4>
<%= form_with model: [@recipe, @recipe.recipe_foods.create] do |form|%>

<% if recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

      <ul>
        <% recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="">
  <%= form.label :food %>
  <div>
    <%= form.select :food_id, Food.all.collect {|food| [food.name, food.id]},{
    include_blank: true} , class:"form-select" %>
  </div>
</div>

<div class="">
  <%= form.label :quantity %>
  <div>
    <%= form.number_field :quantity , class:"form-control" , required: true,
    placeholder: '1', min: 1%>
  </div>
</div>

<div class=""><%= form.submit "Add", class:"btn btn-dark" %></div>
<%end%>
<div class="">
  <%=link_to 'Return to Recipes', recipe_path(@recipe.id), class:"btn btn-link"%>
</div>

app/views/recipe_foods/_recipe_food.html.erb
<div id="<%= dom_id recipe_food %>">
  <p>
    <strong>Quantity:</strong>
    <%= recipe_food.quantity %>
  </p>

  <p>
    <strong>Recipe:</strong>
    <%= recipe_food.recipe_id %>
  </p>

  <p>
    <strong>Food:</strong>
    <%= recipe_food.food_id %>
  </p>

</div>

app/views/recipe_foods/edit.html.erb
<h1>Editing recipe food</h1>

<%= render "form", recipe_food: @recipe_food %>

<br>

<div>
  <%= link_to "Back to recipe foods", recipe_path(@recipe) %>
</div>

app/views/recipe_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipe foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe food", new_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<h1>New recipe food</h1>

<%= render "form", recipe_food: @recipe_food %>

<br>

<div>
  <%= link_to "Back to recipe foods", recipe_foods_path %>
</div>

app/views/recipe_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe_food %>

<div>
  <%= link_to "Edit this recipe food", edit_recipe_food_path(@recipe_food) %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>

  <%= button_to "Destroy this recipe food", @recipe_food, method: :delete %>
</div>